### ISSUE TITLE
TestStats and TestID3D12Device4 failing (master, e56c26d)

### ISSUE THREAD

**Issue by Sergio0694** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#10]
Hello,
I noticed that a couple of tests are currently failing, in particular `TestStats` and `TestID3D12Device4`.
This happens both when running the pre-built executable, as well as when manually building and running the sample.

I'm getting these two errors (the second is after commenting out the first and re-running the tests):

> Test stats
> Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "924" "): !( " "endStats.Total.AllocationCount == begStats.Total.AllocationCount + count" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 924

> Test ID3D12Device4
> Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "1372" "): FAILED( " "ctx.allocator->AllocateMemory1(&allocDesc, &heapAllocInfo, session, &alloc)" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 1372

System info:
- Windows 10 Pro, x64 (build 19041.782)
- GTX 1080 (driver 456.71)

Hope this helps, keep up the good work! 🙌

**Comment by adam-sawicki-a** [comment]
Regarding `TestStats`, I cannot reproduce this failure. It passes for me. Any help with debugging is welcome.

Regarding `TestID3D12Device4`, on my system (Windows 20H2, RTX2080Ti, driver 461.40) that call to `AllocateMemory1` you mentioned causes 100% BSOD! Works fine on AMD cards. D3D Debug Layer doesn't show any error or warning. I commented out this part of test.

**Comment by Sergio0694** [comment]
Hi @adam-sawicki-a, thank you for taking a look!
That BSOD issue is... Uh... Interesting? 😅

As for the `TestStats` failing, I can 100% confirm it repros for me with both the precompiled binary and a local build, and I also asked @john-h-k to repro on his machine, and he could repro the same error with again both the precompiled binary and with a local build. Here's two screens with the errors I'm getting: [prebuilt](https://user-images.githubusercontent.com/10199417/107789137-81a84800-6d51-11eb-97f5-5bdf6250afaa.png) and [local build](https://user-images.githubusercontent.com/10199417/107789170-8cfb7380-6d51-11eb-9f4b-7062a1d9163e.png).

We're basically aalways getting this error:

> ResourceHeapTier = D3D12_RESOURCE_HEAP_TIER_1
TESTS BEGIN
Test virtual blocks
Test committed resources and JSON
Test custom heap flags
Test placed resources
Test other COM interface
Test custom pools
Test aliasing memory
Test mapping
Test stats
Assertion failed: 0 && "C:\Users\johnk\source\repos\D3D12MemoryAllocator\src\Tests.cpp" "(" "924" "): !( " "endStats.Total.AllocationCount == begStats.Total.AllocationCount + count" " )", file C:\Users\johnk\source\repos\D3D12MemoryAllocator\src\Tests.cpp, line 92

Let us know if there's anything specific I can do to help on my end to help debugging this 🙂

**Comment by john-h-k** [comment]
Appears to be due to HEAP_TIER_1 - it reproes on me and sergio's 10xx with HEAP_TIER_1 but not on a 2080 with HEAP_TIER_2

**Comment by tannergooding** [comment]
You can repro by modifying https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/master/src/D3D12MemAlloc.cpp#L4273 to be:

```diff
    hr = m_Device->CheckFeatureSupport(D3D12_FEATURE_D3D12_OPTIONS, &m_D3D12Options, sizeof(m_D3D12Options));
    if(FAILED(hr))
    {
        return hr;
    }

+    m_D3D12Options.ResourceHeapTier = D3D12_RESOURCE_HEAP_TIER_1;
```

**Comment by adam-sawicki-a** [comment]
Thank you for your help! Indeed there was a bug in statistics calculation algorithm when `RESOURCE_HEAP_TIER_1` is active. I fixed it.
