### ISSUE TITLE
Add support for custom heaps (explicit D3D12_HEAP_PROPERTIES)

### ISSUE THREAD

**Issue by Sergio0694** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#11]
## Overview

Let me start by saying that D3D12MA is a great project and it's super easy to integrate, which is awesome 😄

There's one big limitation currently in the way D3D12MA can be used, which is that there is no support for custom heaps. Even when using `Allocator::CreatePool` to create a custom pool, the `POOL_DESC.HeapType` specifically mentions in the documentation not to use the `CUSTOM` heap type, and there is also no way to pass other heap properties for the pool. In general, it would be necessary for `POOL_DESC` to allow callers to pass a `D3D12_HEAP_PROPERTIES` value directly (eg. replacing that single `HeapType` field), so that consumers would have full control on the target heap used for allocations when using that pool.

This would enable a number of scenarios not possible today when using D3D12MA, such as:

- Properly supporting UMA architectures (with a custom heap that's CPU visible)
- Using a custom `DEFAULT` heap that's also CPU visible (using `POOL_L0` and `PAGE_ACCESS_WRITE_BACK`)
- Using a custom `READBACK` heap for transfer buffers that can be both read to and written to by the GPU
- Etc.

## Proposed solution
The simplest solution I can think of would be to just change this field in `POOL_DESC`:

```diff
 struct POOL_DESC
 {
-    D3D12_HEAP_TYPE HeapType;
+    D3D12_HEAP_PROPERTIES HeapProperties;
 };
```

That `HeapProperties` would then be passed internally just like `HeapType` is today, and then `MemoryBlock::Init` would use that `HeapProperties` value to setup the `D3D12_HEAP_DESC` value before calling `ID3D12Device::CreateHeap`, instead of just setting the heap type like it does today. As in, minor changes would need to be done here:

https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/e56c26d8105a679f22860b865f4c074d19006e88/src/D3D12MemAlloc.cpp#L3425-L3435

This would give consumers of the library much greater flexibility, and it'd make the ability to create custom allocation pools much more worthwhile, as there could be way more customization done on the allocation parameters used by them.

**Comment by adam-sawicki-a** [comment]
Thank you for this suggestion. I agree this is a good idea. I will change this together with allowing to create committed allocations out of custom pools. I have it on my TODO list.

**Comment by Sergio0694** [comment]
That's awesome, looking forward to it!
Being able to use custom pools with D3D12MA will allow me to always use it in my project instead of having dedicated paths for when a UMA device is in use (so that I can have a CPU visible custom heap), so really happy you liked this proposal! 😄

**Comment by adam-sawicki-a** [comment]
I pushed the implementation as you suggested to the master branch. I'm sorry it took so long. Please net me know if it works for you.

**Comment by Sergio0694** [comment]
Hey, absolutely not a problem, of course!
I understand time is limited for everyone, I really appreciate you tackling this! 😄

Will start to integrate all these latest changes into the C# port (https://github.com/terrafx/terrafx.interop.d3d12memoryallocator) right away, and then try this out in my own library (https://github.com/Sergio0694/ComputeSharp) where I'm already using D3D12MA through that port I made. Will report back once I've migrated this new feature over and tested it out! 🚀

**Comment by Sergio0694** [comment]
Hi @adam-sawicki-a! So, support for custom pools has been merged in `TerraFX.Interop.D3D12MemoryAllocator` (I also have two more PRs to port your other new changes and optimizations, but that's separate anyway), and I'm working on integrating the new changes into `ComputeSharp` now [in this branch](https://github.com/Sergio0694/ComputeSharp/tree/feature/d3d12ma-uma). First impressions, this is **awesome**! 🎉

I could simplify my code a ton and remove all the dedicated paths for UMA/discrete devices, and now I just always create an allocator for each device, create a custom `L0` pool if the device is UMA, and then always pass that when creating new resources, since D3D12MA will just ignore the pool if it's `null` and use it otherwise, it's super convenient! Great work on that!

I only have one feedback/issue, and that is that right now custom pools don't support committed allocations. I'm using that functionality in my library to let users specify an `AllocationMode` when creating resources, so that if they set it to `Clear` (which is opt-in and not the default one), the library will use a committed resource instead so that the contents will be guaranteed to be cleared (the default mode instead will just pass `NONE` as allocation flags, so that D3D12MA will create a placed resource with whatever contents it might have initially).

Is the fact that this option is not available when using custom heaps a technical limitations, or would it be possible to have it enabled as well to get feature parity to when you're not using a custom heap and just relying on the built-in ones?

Thanks! 😄

**Comment by adam-sawicki-a** [comment]
Thank you for your feedback. You are right. Support for committed allocations in custom pools is on my TODO list and I will implement it soon. I will let you know in this ticket once it is finished. The other issue is also related to that.

**Comment by adam-sawicki-a** [comment]
I added support for committed allocations in custom pools. Please let me know if it works for you.

**Comment by Sergio0694** [comment]
That's awesome, thank you!
I've already ported them and opened a PR into [TerraFX.Interop.D3D12MemoryAllocator](https://github.com/terrafx/terrafx.interop.d3d12memoryallocator), will give this a try as soon as that's merged and the preview package is available. Will post an update when I've had a chance to play with the new feature in my project 😄

**Comment by adam-sawicki-a** [comment]
Thank you for finding this issue. It was a major bug which I hopefully fixed now. Please let me know if it works for you or if you have any additional questions or suggestions.

**Comment by Sergio0694** [comment]
That's awesome, and no worries for the delay at all! 😄
Thank you for looking into this, I'll go ahead and port the new commits to finish https://github.com/terrafx/terrafx.interop.d3d12memoryallocator/pull/9, and will double check that everything works fine on my end as well. Keep up the great work, D3D12MA is brilliant! 🙌
