### ISSUE TITLE
4 test failures when using WARP device

### ISSUE THREAD

**Issue by Sergio0694** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#12]
Hello,
I was trying out `D3D12MA` when using the WARP device and I noticed that 4 tests are failing in that case.
Specifically: `TestPlacedResources`, `TestCustomPools`, `TestDevice4` and `TestDevice8`.

## Repro steps
- Change this check to `!= 0` to select the WARP device:

https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/5457bcdaee73ee1f3fe6027bbabf959119f88b3d/src/D3D12Sample.cpp#L388

- Run the tests again

## Errors list
I get the following failures (each seen after commenting out the previously failing test and re-running the tests):

> Test placed resources
Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "455" "): !( " "resources[i].allocation->GetHeap() != NULL" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 455

> Test custom pools
Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "683" "): FAILED( " "hr" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 683

> Test ID3D12Device4
Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "1348" "): FAILED( " "dev4->CreateProtectedResourceSession(&sessionDesc, IID_PPV_ARGS(&session))" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 1348

> Test ID3D12Device8
Assertion failed: 0 && "C:\\Users\\Sergio\\Documents\\GitHub\\D3D12MemoryAllocator\\src\\Tests.cpp" "(" "1412" "): !( " "alloc1->GetHeap()!= NULL" " )", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 1412

### Fix for `TestDevice4`
Not sure about the failures in the other tests, but I could investigate and fix the one in this one.
Turns out the WARP device doesn't support `ID3D12Device4::CreateProtectedResourceSession`, so the call to this method at the start of the test just causes `ERROR_INVALID_PARAMETER` to be returned. The fix is to just do something like:

```cpp
D3D12_FEATURE_DATA_PROTECTED_RESOURCE_SESSION_SUPPORT support;
CHECK_HR(ctx.device->CheckFeatureSupport(
    D3D12_FEATURE::D3D12_FEATURE_PROTECTED_RESOURCE_SESSION_SUPPORT,
    &support,
    sizeof(D3D12_FEATURE_DATA_PROTECTED_RESOURCE_SESSION_SUPPORT)));

if (support.Support == D3D12_PROTECTED_RESOURCE_SESSION_SUPPORT_FLAGS::D3D12_PROTECTED_RESOURCE_SESSION_SUPPORT_FLAG_NONE)
{
    wprintf(L"Skipping ID3D12Device4\n");
    return;
}
```

Hope this helps! 😄

**Comment by Sergio0694** [comment]
Tried again as of e37363c0f1cb015cdd70252a59d3356a98b999db and the errors seem to be gone now, I can run all tests with the WARP device and they run just fine. The only two remaining errors which I get are with my GTX 1080, specifically:

> Test placed resources
Assertion failed: 0 && "resources[i].allocation->GetHeap() != NULL", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 463

> Test ID3D12Device8
Assertion failed: 0 && "alloc1->GetHeap()!= NULL", file C:\Users\Sergio\Documents\GitHub\D3D12MemoryAllocator\src\Tests.cpp, line 1562

Which I've already mentioned [here](https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/issues/11#issuecomment-803393276), so I guess they're already being tracked in #11? @adam-sawicki-a if so feel free to close this issue, as these 4 errors with the WARP device specifically should be fixed now. Seems like those two remaining ones are the last missing bit to get everything running perfectly with all the latest changes to support custom heaps! 😄

Related question: I see that #11 is still marked as "input needed" - do you need any other info on my end?
If so, let me know and I'll be happy to help!

**Comment by adam-sawicki-a** [comment]
Thank you for the suggestions and sorry for delayed response. I added query for `D3D12_FEATURE_PROTECTED_RESOURCE_SESSION_SUPPORT` to the testing code.
