### ISSUE TITLE
D3D12MA_DXGI_1_4 always 0 unless dxgi1_4.h included before

### ISSUE THREAD

**Issue by Aldarrion** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#13]
Hello,
after updating the allocator in our project from an older version, I've noticed, that [ebf4f8de094c41b10f5b111fe88189f85d9ea8f0](https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/commit/ebf4f8de094c41b10f5b111fe88189f85d9ea8f0) introduced a new condition to when is the `D3D12MA_DXGI_1_4` macro defined to `1`.

```
#ifdef __IDXGIAdapter3_INTERFACE_DEFINED__
    #define D3D12MA_DXGI_1_4 1
#else
    #define D3D12MA_DXGI_1_4 0
#endif
```

Correct me if I'm wrong but since there are no includes before this block, unless someone either includes `dxgi1_4.h` before their `D3D12MemAlloc.h` or define the macro manually (which is not advised in my opinion) the `D3D12MA_DXGI_1_4` will always be `0`.

I understand the usage of the other `..._INTERFACE_DEFINED__` conditions since they are defined in the `d3d12.h`. However, even if we moved the block in question after the `dxgi.h` include it would not help since the dxgi headers are versioned. So to have the `__IDXGIAdapter3_INTERFACE_DEFINED__` defined we would need to include `dxgi1_4.h` or greater which is actually predicated in the `.cpp` by `D3D12MA_DXGI_1_4` being non-zero.

Is this a bug or did I misuderstand the intention/usage?

**Comment by adam-sawicki-a** [comment]
You are right! I pushed some fix. Please let me know if it works for you.

**Comment by Aldarrion** [comment]
Nice, the fix works fine for me, thanks!
