### ISSUE TITLE
Support usage from C?

### ISSUE THREAD

**Issue by mguerret-amd** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#14]
DX12 (like most Microsoft COM API) is available in C. However, this memory allocator is not.

Would it be possible to expose a C interface for the allocator?

**Comment by adam-sawicki-a** [comment]
I am sorry but this library is written as a C++ project and support for C is not planned. Ports or bindings to other languages are welcome as external projects.

Please note the API of this library is not based on COM, although looks similar. It is a regular object-oriented C++.
