### ISSUE TITLE
D3D12 Memory Alloc Question

### ISSUE THREAD

**Issue by lygyue** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#15]
Hi, I am doing d3d12 programing. it's a few people do the similar work and it's very difficult to find someone to communication.
I am try to create a texture, my code like this:
`
	D3D12_HEAP_PROPERTIES HeapPro;
	BuildTextureHeapPro(HeapPro);
	D3D12_RESOURCE_DESC TextureDesc;
	BuildTextureDesc(TextureDesc);
	TextureDesc.Alignment = 65536;

	D3D12_RESOURCE_ALLOCATION_INFO Info;
	Info = Device->GetResourceAllocationInfo(0, 1, &TextureDesc);
	mTextureLen = (int)Info.SizeInBytes;
`
It works ok in most times.
But when the texture width is 1108 and the height is 1440, B8G8R8A8 format,  Info.SizeInBytes return a wrong size, which return 6619136. and 1108 * 1440 * 4 = 6382080.  I try another way, for example, i try "Device->GetCopyableFootprints(&TextureDesc, 0, 1, 0, &Layouts, nullptr, &RowSizeInBytes, &RequiredSize);", and RequiredSize is 6635344, and it is not the right value. I think the right value is 6635520. Because the row pitch is 4608 and the right value is 4608 * 1440 = 6635520.
what is the problem? i google for days and can't find the solution.
please help, thankyou!

**Comment by lygyue** [comment]
when i create a uploaded buffer for texture uploaded and the buffer size is 6619136, the texture uploaded will failed because the Device->GetCopyableFootprints(&TextureDesc, 0, 1, 0, &Layouts, nullptr, &RowSizeInBytes, &RequiredSize); return RequiredSize is 6635344, I uploaded the texture using microsoft's sample code:UpdateSubresources, it will return when :IntermediateDesc.Width < RequiredSize + pLayouts[0].Offset.

**Comment by lygyue** [comment]
I means the value which GetResourceAllocationInfo return must larger than GetCopyableFootprints returns. and in my situation 6619136 is smaller than 6635520 , it doesn't work, and i don't know why.

**Comment by lygyue** [comment]
I soloved this in this way:
`	D3D12_RESOURCE_ALLOCATION_INFO Info;
	Info = Device->GetResourceAllocationInfo(0, 1, &TextureDesc);
	UINT64 RequiredSize = 0;
	UINT64 RowSizeInBytes = 0;
	D3D12_PLACED_SUBRESOURCE_FOOTPRINT Layouts;
	Device->GetCopyableFootprints(&TextureDesc, 0, 1, 0, &Layouts, nullptr, &RowSizeInBytes, &RequiredSize);
	if (RequiredSize > Info.SizeInBytes)
	{
		mTextureLen = ((int)RequiredSize + (int)Info.Alignment - 1) / (int)Info.Alignment * (int)Info.Alignment;
	}
	else
	{
		mTextureLen = (int)Info.SizeInBytes;
	}`
But i can't ensure is the right way.

**Comment by lygyue** [comment]
D3D12_RESOURCE_ALLOCATION_INFO Info;
	Info = Device->GetResourceAllocationInfo(0, 1, &TextureDesc);
	UINT64 RequiredSize = 0;
	UINT64 RowSizeInBytes = 0;
	D3D12_PLACED_SUBRESOURCE_FOOTPRINT Layouts;
	Device->GetCopyableFootprints(&TextureDesc, 0, 1, 0, &Layouts, nullptr, &RowSizeInBytes, &RequiredSize);
	if (RequiredSize > Info.SizeInBytes)
	{
		mTextureLen = ((int)RequiredSize + (int)Info.Alignment - 1) / (int)Info.Alignment * (int)Info.Alignment;
	}
	else
	{
		mTextureLen = (int)Info.SizeInBytes;
	}

**Comment by adam-sawicki-a** [comment]
I am sorry but this place is for reporting issues or feature request for this specific project - D3D12 Memory Allocator. For general questions about DirectX please refer to the official places provided by Microsoft e.g. https://devblogs.microsoft.com/directx/ and their Discord server. You can ask for help there.
