### ISSUE TITLE
VS2015 compiles?

### ISSUE THREAD

**Issue by zhaijialong** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#2]
Hi.
I tried to use `D3D12MemAlloc.h/cpp` in our VS2015 project, and it had many compilation errors. Could we get VS2015 fix?

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. Indeed I develop the project using Visual Studio 2017 and 2019, I didn't test it in 2015 version.

It would be useful if you provided more details, e.g. what compilation errors do you see?

**Comment by zhaijialong** [comment]
Hi, @adam-sawicki-a .
First, thanks for your great work.

In the `struct Budget`, it has a member named `Budget`, that results compilation error in VS2015. And there is many template related erorrs which I didn't look into them.
