### ISSUE TITLE
Sporadic issues when copying between 3D textures with D3D12MA + WARP device

### ISSUE THREAD

**Issue by Sergio0694** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#24]
Hi there! 👋
I've stumbled upon a weird issue while writing unit tests for my library [ComputeSharp](https://github.com/Sergio0694/ComputeSharp), which uses a [1:1 C# port](https://github.com/terrafx/terrafx.interop.d3d12memoryallocator) of D3D12MA, and I'm investigating it to try to narrow down the root cause. I thought I'd also open an issue here for tracking as it seems to be related to D3D12MA (I've verified I cannot repro it if I just allocate my resources with `ID3D12Device::CreateCommittedResource`) in some way.

I don't yet have a full minimal repro, but here's the general idea:
- This issue only happens when using a WARP device.
- This issue also only happens when using D3D12MA and a custom pool ([here](https://github.com/Sergio0694/ComputeSharp/blob/00fc0f3b12f764968cfbf147ee898b7b0a1a3f27/src/ComputeSharp/Graphics/Extensions/Interop/AllocatorExtensions.cs#L27)) for UMA devices.
- This issue only happens when working with 3D textures and copying data between them.
- I can only reproduce the issue when the test in question is running **after** another one with different parameters. If I run it on its own, it passes fine. This makes me think it might be somewhat related to how D3D12MA is reusing allocations.
- I can repro this on 2 different machines with Windows 11. I've had another dev run the tests on his Windows 10 machine and they all passed. Another dev on another Windows 10 machine instead has even more tests failing for whatever reason.

The repro steps I have so far:

- Create a WARP device with `D3D_FEATURE_LEVEL_11_0`
- Create a copy command queue, fence, etc. (the usual setup)
- Create a D3D12MA allocator, and a pool with these parameters:

```csharp
D3D12MA_POOL_DESC poolDesc = default;
poolDesc.HeapProperties.CreationNodeMask = 1;
poolDesc.HeapProperties.VisibleNodeMask = 1;
poolDesc.HeapProperties.Type = D3D12_HEAP_TYPE_CUSTOM;
poolDesc.HeapProperties.CPUPageProperty = D3D12_CPU_PAGE_PROPERTY_WRITE_BACK;
poolDesc.HeapProperties.MemoryPoolPreference = D3D12_MEMORY_POOL_L0;
```

- Create a 3D texture with `DXGI_FORMAT_R32_FLOAT` format, `D3D12_RESOURCE_FLAG_NONE` flags, `D3D12_RESOURCE_STATE_COMMON` state, `D3D12_HEAP_TYPE_DEFAULT` heap, `D3D12MA_ALLOCATION_FLAG_NONE` D3D12MA flags, with the UMA pool.
- Fill this texture with sample data, by creating an upload buffer with the allocator (`D3D12_HEAP_TYPE_UPLOAD`, `D3D12_RESOURCE_FLAG_NONE`, `D3D12_RESOURCE_STATE_GENERIC_READ`), using the right byte size depending on the copyable footprint retrieved from the previously allocated 3D texture. Map this resource, write the sample data to it, then create a copy command list and use `ID3D12GraphicsCommandList::CopyTextureRegion` to copy this data to the actual texture.
- Create another 3D texture, leave this uninitialized (ie. use `D3D12MA_ALLOCATION_FLAG_COMMITTED` to force zeroing).
- Copy a given volume from the first 3D texture to this new texture (`ID3D12GraphicsCommandList::CopyTextureRegion`).
- Copy the entire second 3D texture back to be able to verify its contents after the previous copy. That is, allocate a readback buffer just like the upload buffer before, call `ID3D12GraphicsCommandList::CopyTextureRegion` to it, then map it and copy its contents somewhere you can easily read from (or alternatively just map the buffer and then read directly from there).

Now, running these 2 tests one after the other causes the second one to fail:
1) First test (passing ✅):
    - Source texture size: (512, 512, 3)
    - Destination texture size: (512, 512, 3)
    - Source copy offsets: (0, 0, 0)
    - Destination copy offsets: (0, 0, 1)
    - Copy volume size: (512, 512, 2)
2) Second test (failing ❌):
    - Source texture size: (512, 512, 3)
    - Destination texture size: (512, 512, 4)
    - Source copy offsets: (0, 0, 1)
    - Destination copy offsets: (0, 0, 2)
    - Copy volume size: (512, 512, 2)

By "test failing", I mean that when verifying the data read back from the second texture (the destination one), I get this:
- The depth level 0 is correctly all zeroed ✅
- The depth level 1 is not zeroed. It seems to still have the data from the previous test run, where items were copied at destination dpeth level 1 in the second texture. This time instead the destination depth level is 2, so depth level 1 should just all be 0. We're explicitly passing `D3D12MA_ALLOCATION_FLAG_COMMITTED` for the destination texture, so it should always be a new allocation with no previous data in it. ❌
- Depth levels 2 and 3 are correctly holding the data copied from the source texture ✅

Just a random thought, but if D3D12MA is in fact accidentlaly not using a committed allocation here and reusing a previous one, it might explain why the behavior is so inconsistent across different OS versions and machines, as the exact way previous allocations are reused and cleared by the OS/driver is undefined? Anyway this is as detailed I could be for this, let me know if there's anything else I can do! I can also try to actually come up with a minimal repro if it helps (though that'd be in C#).

Thanks! 😄

**Comment by adam-sawicki-a** [comment]
Hi 😀

Thank you for reporting this issue. Indeed it sounds very weird. I think the best test to check whether D3D12MA library is the culprit would be to implement the logic of this test without using this library, just allocating DX12 memory with native `CreateCommittedResource`/`CreateHeap` - of course using committed versus placed resources same way as in the original test.

**Comment by Sergio0694** [comment]
Hi Adam, thank you for the quick reply!
I did verify that D3D12MA is somehow related (or at least that the specific usage of DX12 APIs it uses causes the issue), in fact removing it and just doing `CreatedCommittedResource` for both textures does not cause the same issue (that's why I also logged the issue here and not just pinged the DirectX/WARP team about this). I guess this likely means that either it's an issue related to D3D12MA, or with just combining a custom heap + created resource, with a committed allocation, which is what I think D3D12MA is using in this scenario. I'll see if I have time to properly create a minimal repro (it's a bit tricky to pull out all the relevant code from the rest of the library as you can imagine 😄) and to do the test you mentioned with also a custom heap and a placed resource for the first 3D texture. I'll post an update when I have more info! 🙂

**Comment by adam-sawicki-a** [comment]
The most common problem when starting using an allocation library is implicitly relying on resources being initialized with zeros, as DX12 does when allocating as committed. When allocated as placed, same memory may be reused and may contain garbage data. You may also check this article: https://asawicki.info/news_1724_initializing_dx12_textures_after_allocation_and_aliasing

Another common mistake is relying on a resource starting at offset 0 in a memory block, but this affect mostly Vulkan, as DX12 API has no place where an offset from the beginning of a heap to the resource would be used - we always refer to the resource itself.

I am also thinking about whether it can have something to do with alignment, but D3D12MA automatically queries alignment required by the resource from DX12 and respects it. A thing to try could be:
```cpp
#define D3D12MA_USE_SMALL_RESOURCE_PLACEMENT_ALIGNMENT 0
```

**Comment by Sergio0694** [comment]
Yeah I'm thinking there's definitely a possibility that this is just intended behavior with D3D12MA, but my confusion is: if I'm allocating a resource passing the `D3D12MA_ALLOCATION_FLAG_COMMITTED` (which is the case for my second texture), shouldn't that always result in a new texture being allocated, with guaranteed zeroing (which the DX12 runtime does by default on new committed allocations)? As in, that's currently what I'm using in my library to let users opt-in into zeroed allocations 🤔

**Comment by adam-sawicki-a** [comment]
Yes, if you specify `D3D12MA_ALLOCATION_FLAG_COMMITTED` then the library should always allocate as committed and then the resource should be filled with zeros, as far as I know. But it is worth checking if manual initialization of the resource would solve the problem.

**Comment by Sergio0694** [comment]
Right, that was a good idea! I've added an explicit zeroing to the destination texture right before copying, and this does indeed make my tests pass. This would suggest that D3D12MA is in fact giving me a 3D texture that is not zeroed, even though I'm passing the `D3D12MA_ALLOCATION_FLAG_COMMITTED` flag when allocating it. I've also double checked by just immediately copying the allocated texture back and verifying that all items are initially 0, and this in fact not the case for that one test: the texture seems to still have the values it had in the previous test run. Maybe there's some corner case in D3D12MA where `D3D12MA_ALLOCATION_FLAG_COMMITTED` isn't being respected? 🤔

**Comment by adam-sawicki-a** [comment]
I added a test to make sure allocations made as committed out of custom pools are really committed and it passes. I suspect this is Microsoft WARP implementation not really zeroing the memory of a committed allocation. I suggest to contact Microsoft regarding this issue.

**Comment by Sergio0694** [comment]
Thank you for adding a test! And yeah, I also had a hunch this could very well just be an issue with WARP (wouldn't be the first time something like this happens), I just figured I'd mention this to you as well given that I can only repro this when using D3D12MA, at least in my use case (as I'm not using the combination of custom pool + placed resources + committed allocations otherwise).
Thank you for looking into this too!

I'll go ping the WARP team and post an update when I hear back from them! 😄

**Comment by adam-sawicki-a** [comment]
Thank you. Please also ask them whether users (of the real hardware GPU) can assume newly allocated memory like committed resources or heaps is really filled with zeros. I assumed yes based on this article: https://devblogs.microsoft.com/directx/coming-to-directx-12-more-control-over-memory-allocation/ but this may not be true.

**Comment by Sergio0694** [comment]
So, the DirectX team confirmed that you can definitely rely on committed allocations zeroing data, as mentioned in that post:

> "Committed Resources should always be zeroed unless you happened to specify the `NOT_ZEROED` flag"

When I have some time I'll try to put together a minimal repro without D3D12MA I can share with the WARP team 🙂
