### ISSUE TITLE
StrStrI identifier is undefined

### ISSUE THREAD

**Issue by EducatedMF** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#27]
StrStrI is undefined no matter what I do.

I've included it like this:

#include <shlwapi.h>
#inc....
#pragma comment (lib, "Shlwapi.lib")

Please help.

**Comment by adam-sawicki-a** [comment]
What IDE/compiler and Windows SDK are you using? According to Microsoft documentation, the function is defined in "shlwapi.h", so if it is not defined for you, there must be something wrong with your development environment.

https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-strstria

**Comment by EducatedMF** [comment]
Hey Adam,
I'm using the Visual Studio 2022 IDE and Windows SDK 10.0.19041.0. 

I haven't been able to solve this still ot says:
error C3861: 'StrStrI': identifier not found.

**Comment by adam-sawicki-a** [comment]
Were you able to solve the issue?

**Comment by EducatedMF** [comment]
No, im gonna write my own memory manager
