### ISSUE TITLE
Comptr Issues.

### ISSUE THREAD

**Issue by oglake** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#28]
Hi, I'm currently trying to implement this library with com smart pointers, but I've run into a problem.

When I use Microsoft::WRL::ComPtr<D3D12MA::Allocator> allocator, I get the following compiler warning.

C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt\wrl/client.h(235,1): error C2440: '=': cannot convert from 'void' to 'unsigned long' [C:\Users\username\source\repos\D3D12\build\D3D12.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt\wrl/client.h(235,32): message : Expressions of type void cannot be converted to other types [C:\Users\username\source\repos\D3D12\build\D3D12.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt\wrl/client.h(228): message : while compiling class template member function 'unsigned long Microsoft::WRL::ComPtr<D3D12MA::Allocator>::InternalRelease(void) noexcept' [C:\Users\username\source\repos\D3D12\build\D3D12.vcxproj]
[build] C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\winrt\wrl/client.h(290): message : see reference to function template instantiation 'unsigned long Microsoft::WRL::ComPtr<D3D12MA::Allocator>::InternalRelease(void) noexcept' being compiled [C:\Users\username\source\repos\D3D12\build\D3D12.vcxproj]
[build] C:\Users\username\source\repos\D3D12\src\DXWindow.hpp(73): message : see reference to class template instantiation 'Microsoft::WRL::ComPtr<D3D12MA::Allocator>' being compiled [C:\Users\username\source\repos\D3D12\build\D3D12.vcxproj]

However if I use CComPtr<D3D12MA::Allocator> allocator everything works fine.

The gpuopen docs says this library should work with WRL pointers. 

I don't know if I should be mixing both types of smart pointer as my other com objects are using WRL.

Any help is appreciated, thanks.

**Comment by adam-sawicki-a** [comment]
Sample application and test suite uses `Microsoft::WRL::ComPtr` from WRL and it works fine. See files: src\D3D12Sample.cpp, src\Tests.cpp. Please double-check if you use `ComPtr` correctly. What instruction shows this compiler error?

**Comment by oglake** [comment]
No Instructions, If I compile the memory allocator with Microsoft::WRL::ComPtr I get that error.
I just tried your test sample, and I'm getting the same error. 
I also got this error using your test "error C2039: 'MinAllocationAlignment': is not a member of 'D3D12MA::POOL_DESC"
When I remove that line, then I get the previous error.
![Screenshot 2021-12-21 213213](https://user-images.githubusercontent.com/88506370/147025243-084b73e7-5e55-4375-a7f0-bbf778585a55.png)
![Screenshot 2021-12-21 213124](https://user-images.githubusercontent.com/88506370/147025246-94a308c4-38e3-45ec-973d-445c13048606.png)
I have attached screenshots.
Also, I don't know if it makes a difference but I am using VS2022 and I changed my windows sdk to win10 as I was using w11 previously.
Please let me know what config you are using.
Thank you.

**Comment by oglake** [comment]
I have solved the issue. The problem was with the version of the memory allocator I was using, I was wondering why my 
D3D12MA::POOL_DESC wouldn't have MinAllocationAlignment.

I am using vcpkg and that version is the cause of the problem. I got the .h and .cpp from the repo, and everything works fine.
Thank you for your help.
