### ISSUE TITLE
D3D12MA_DEBUG_GLOBAL_MUTEX causes double lock on Release

### ISSUE THREAD

**Issue by Armageddonw** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#29]
Defining D3D12MA_DEBUG_GLOBAL_MUTEX causes double locking of static debug std::mutex when releasing resources.

See  IUnknownImpl::Release():
```
ULONG STDMETHODCALLTYPE IUnknownImpl::Release()
{
    D3D12MA_DEBUG_GLOBAL_MUTEX_LOCK

    const uint32_t newRefCount = --m_RefCount;
    if(newRefCount == 0)
        ReleaseThis();
    return newRefCount;
}
```

When m_RefCount == 0, ReleaseThis(), tries to acquire debug lock again:

```
void Allocator::ReleaseThis()
{
    D3D12MA_DEBUG_GLOBAL_MUTEX_LOCK
    ...
}
```
Resulting in std::system_exception being thrown.

**Comment by adam-sawicki-a** [comment]
Thank you for finding this. It has been fixed.
