### ISSUE TITLE
Release build v1.0.0+vs2017 problem

### ISSUE THREAD

**Issue by R-Michelsen** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#3]
There seems to be a bug in the release build that prevents me from compiling the allocator.
In particular on line 596 `m_Allocator` is referenced but not declared anywhere I can find.
```C#
596: Free(m_Allocator.m_pCallbacks, m_pArray)
```

The issue seems to be fixed on the master branch as I can compile without issues there, I thought I'd open an issue to let you know though. Thanks for the work!

**Comment by adam-sawicki-a** [comment]
What compiler do you use? I checked Visual Studio 2017 as well as 2019 and the release "v1.0.0+vs2017" compiles OK. I agree this is a bug. However, the function `reserve` is never used, so Microsoft compiler ignores it.

In order to have it fixed I recommend taking latest version from "master" branch, which is always in a good functional state and contains many additional features and fixes.

**Comment by R-Michelsen** [comment]
Im using Visual Studio 2019 Version 16.4.4. The compilation error seems to happen during template instantiation, here is the compiler output.
```C++
1>C:\Users\Rasmus\Desktop\Untitled\Untitled\Dependencies\D3D12MemoryAllocator\include\D3D12MA\D3D12MemAlloc.cpp(596,18): error C3861: 'm_Allocator': identifier not found
1>C:\Users\Rasmus\Desktop\Untitled\Untitled\Dependencies\D3D12MemoryAllocator\include\D3D12MA\D3D12MemAlloc.cpp(721): message : see reference to class template instantiation 'D3D12MA::Vector<T>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\chrono(632): message : see reference to class template instantiation 'std::chrono::duration<double,std::ratio<1,1>>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\chrono(178): message : see reference to class template instantiation 'std::chrono::duration<__int64,std::nano>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\chrono(610): message : see reference to class template instantiation 'std::chrono::time_point<std::chrono::steady_clock,std::chrono::nanoseconds>' being compiled
```

**Comment by adam-sawicki-a** [comment]
In version 16.4.5 it compiles successfully.
