### ISSUE TITLE
FindAtOffset compile error with GDK

### ISSUE THREAD

**Issue by shaggie76** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#30]
Building with GDK tools for console I'm getting a compile error with the latest release:

`d3d12memalloc.cpp(3557): error C2440: 'return': cannot convert from 'D3D12MA::List<D3D12MA::Suballocation>::const_reverse_iterator' to 'D3D12MA::List<D3D12MA::Suballocation>::const_iterator'
`

My fix was to forward declare const_reverse_iterator right after the forward declaration of reverse_iterator on line 1564; 

    class const_reverse_iterator;

It seems as though "friend class const_reverse_iterator" automatically forward-declares the type for VS2017 but it's somehow ambiguous with the GDK toolchain so the conversion constructors aren't triggered automatically.

Sorry if this should be a PR instead -- it's a one-line fix.

**Comment by adam-sawicki-a** [comment]
Thank you for finding this issue and describing the exact fix. I fixed it.
