### ISSUE TITLE
Stats inside ASSERT conditional

### ISSUE THREAD

**Issue by alvar-ava** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#34]
When trying this code out I got a warning: warning C4706: assignment within conditional expression
it looks like if the assert isn't defined, the assignment will not be made. Is this intentional?
https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/d0cc54c5ad88b5fb7b4f861d5f78f695c1ab7215/src/D3D12MemAlloc.cpp#L7026
Also please excuse me if this is not the right way to ask questions like this, I'm not used to the GitHub environment

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this bug. I fixed it.
