### ISSUE TITLE
Offset is not correctly written when exporting to json

### ISSUE THREAD

**Issue by Rob1B** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#35]
Hi !

After diving into a json detailed allocation map, I found a lot of offset that had the same value. 

It looks like it is a simple switch of arguments : 

The definition of PrintDetailedMap_Allocation is this one : 
`void BlockMetadata::PrintDetailedMap_Allocation(JsonWriter& json,
    UINT64 offset, UINT64 size, void* privateData) const`

but it is called like that 
` PrintDetailedMap_Allocation(json, block->size, block->offset, block->PrivateData());` in `BlockMetadata_TLSF::WriteAllocationInfoToJson` (D3D12MemAlloc.cpp:5606).

If it is not this simple thing, I don't understand why nearly all my allocations have the same offset as my size. If it is, it could have be a PR but I wasn't sure.

**Comment by adam-sawicki-a** [comment]
Please note that JSON format is going to change very soon 😀
