### ISSUE TITLE
Regarding D3D12_HEAP_FLAG_CREATE_NOT_ZEROED

### ISSUE THREAD

**Issue by rbertin-aso** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#47]
Hi Adam ! Hope everything is ok ! 

I wanted to know if something was a feature or more of a bug. 

I have a resource that is created with the allocator. By default, this resource (because it can be created without the allocator) is using the D3D12_HEAP_FLAGS : D3D12_HEAP_FLAG_CREATE_NOT_ZEROED. Because of this extra flag, the function `CalcDefaultPoolIndex` considers that the resource should not be created in a default pool, return -1 and the resource will be created as committed. 

Is it the correct behaviour or should it be created as placed (since a placed resource will never be zeroed) ?

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue.

In general, this is a feature. See documentation of `ALLOCATION_DESC::ExtraHeapFlags`: http://localhost:8000/struct_d3_d12_m_a_1_1_a_l_l_o_c_a_t_i_o_n___d_e_s_c.html#a97878838f976b2d1e6b1a76881035690 which says:
> You can specify additional flags if needed. Then the memory will always be allocated as separate block using D3D12Device::CreateCommittedResource or CreateHeap, not as part of an existing larget block.

However, in case when the whole allocator was created with `ALLOCATOR_FLAG_DEFAULT_POOLS_NOT_ZEROED`, specifying `D3D12_HEAP_FLAG_CREATE_NOT_ZEROED` should be able to use default pools. I committed a fix for this case.

Please note that `NOT_ZEROED` flags are about the creation of new D3D12 heaps. If an allocation is placed inside an existing bigger heap with memory reused after previous allocations, obviously it won't be initialized with zeros, it can contain garbage data.

**Comment by rbertin-aso** [comment]
Thanks for the answer and for the fix. I had forgotten the `ALLOCATOR_FLAG_DEFAULT_POOLS_NOT_ZEROED` flag ! 

I'll close the issue ! 
Happy new Year !
