### ISSUE TITLE
32-bit compile error: ambiguous call to JsonWriter::WriteNumber with SIZE_T input.

### ISSUE THREAD

**Issue by kch86** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#49]
```
D3D12MemoryAllocator\src\D3D12MemAlloc.cpp(7184,21): error C2668: 'D3D12MA::JsonWriter::WriteNumber': ambiguous call to overloaded function
D3D12MemoryAllocator\src\D3D12MemAlloc.cpp(1505,18): message : could be 'void D3D12MA::JsonWriter::WriteNumber(UINT64)'
D3D12MemoryAllocator\src\D3D12MemAlloc.cpp(1498,18): message : or       'void D3D12MA::JsonWriter::WriteNumber(UINT)'
```

coming from:
```
json.WriteNumber(m_AdapterDesc.DedicatedVideoMemory);
json.WriteNumber(m_AdapterDesc.DedicatedSystemMemory);
json.WriteNumber(m_AdapterDesc.SharedSystemMemory);
```

**Comment by kch86** [comment]
Oh it looks like this was fixed on master already. In trying to generate repro steps I couldn't repro with latest master. On the PC I ran into this, I was synced to 2.01 tag. 

FIxed with https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/commit/eace86c42911c8812841043d8f34c7574acee7da

Sorry for not checking lastest master first!

**Comment by adam-sawicki-a** [comment]
That's right. Official releases are not created too often, I'm sorry for that. Main branch is always kept in a good state, so I recommend to use latest code from it.

**Comment by kch86** [comment]
No worries, I'll sync to latest. Thanks!
