### ISSUE TITLE
Question about ALLOCATION_FLAG_WITHIN_BUDGET flag

### ISSUE THREAD

**Issue by omd24** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#52]
Hi there, does setting the `ALLOCATION_FLAG_WITHIN_BUDGET` flag enforce using only gpu/device memory or does it also include system memory that is shared for gpu? In other words, how can we specify the followings?
1. "only use dedicated gpu memory" 
2. "use system memory if running out of device memory"
3. "use disk if running out of system and gpu memory"

**Comment by adam-sawicki-a** [comment]
Hi, the flag `ALLOCATION_FLAG_WITHIN_BUDGET` doesn't guarantee that only GPU memory will be used and fallback to system memory will be disabled. It makes D3D12MA check for the budget and fail the allocation when exceeded. Sticking to the budget can increase chance that critical resources won't end up in system memory, making them slower to use, but there are no guarantees. In D3D12 there is no explicit control over these things. We can only allocate in predefined heaps - `UPLOAD`, `DEFAULT`, `READBACK`, which should map to appropriate memory types.

But the budget reported for "local" (GPU) memory, whether queried with `GetBudget` or applied using `ALLOCATION_FLAG_WITHIN_BUDGET` flag when allocating from `DEFAULT`, should include only available VRAM, so not exceeding it is the best thing we can do to ensure good performance.

**Comment by omd24** [comment]
I guess it's a little bit off-topic, but is the `VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT` in VMA behave the same way as `ALLOCATION_FLAG_WITHIN_BUDGET`? or the dx12 flag is more relaxed (because of lack of explicit control)? I mean is it possible to achieve the granularity I asked above with VMA (using a Vulkan backend) or is there always a chance for fallback from gpu to system memory?

**Comment by adam-sawicki-a** [comment]
This flag behaves similarly in both libraries. The main difference is that in VMA there is an automatic fallback to other memory types and heaps in case of allocation failure or (when `WITHIN_BUDGET` flag is set) when exceeding the budget. See the loop inside `VmaAllocator_T::AllocateMemory`: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/master/include/vk_mem_alloc.h#L15073.

If you want to restrict allocation to GPU memory only (equivalent of `DEFAULT` heap in D3D12), you can set `VmaAllocationCreateInfo::requiredFlags` to `DEVICE_LOCAL` or `VmaAllocationCreateInfo::memoryTypeBits` to the bit mask of only restricted set of memory types. Still, there is no guarantee that some memory blocks won't be migrated to system memory in a way transparent to the DX12/Vulkan developer.

**Comment by omd24** [comment]
I see. Thanks for the explanations 🙏
