### ISSUE TITLE
Question about support for deferring block frees

### ISSUE THREAD

**Issue by lmagder** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#53]
Hi, I'm attempting to replicate an allocation scheme used on non-PC platforms for transient resources visible to the GPU only which relies on aliasing the same memory across the frame. This relies on being able to "free" (from the application's POV) the resource memory as soon as it is no longer needed, even if midway through recording a command list, and then allocate new placed resources on top of the same memory so that within a frame GPU memory can be reused via aliasing. 

It seems like using a D3D12MA::Pool object almost supports this since I could make one for these transient allocations and then use AllocateMemory to suballocate the heaps it manages. However, the problem is that releasing the D3D12MA::Allocator will immediately free the underlying ID3D12Heap if that block has now become empty even though the frames using that memory are still in flight. I could avoid this by holding onto the Allocation object until I'm sure the GPU is is finished with the last frame using that memory, although that would prevent any aliasing and frames N, N+1, N+2 would then each have their own copy instead of reusing the same memory, which is undesirable.

Is there some existing mechanism to prevent the underlying heaps from being actually freed when the pool shrinks for some N frames as observed via Allocator::SetCurrentFrameIndex()? I see POOL_DESC::MinBlockCount, which keeps empty blocks around, but I don't have a specific minimum size. Ideally the pool would resize dynamically, but the empty blocks would stick around for N frames after they were last used via a cooldown, where N is the number of frames my application has in flight at a given time. It would also be valid for them to be reused to allocate new resources, similar to reuse within a frame since my application ensures work using the memory doesn't overlap, which is why it seems like the existing behavior is so close to what I'm trying to do.

Am I missing something here? Maybe there is a non-obvious D3D12 behavior that makes this kind of setup impossible? :)

Thanks!

EDIT: I just realized after writing this that if it was possible to dynamically change MinBlockCount on a Pool I could call Pool::GetStatistics() each frame then set the MinBlockCount to the N-frame max of Statistics::BlockCount which would essentially do this behavior

**Comment by adam-sawicki-a** [comment]
Hi, aliasing transient resources that are used only temporarily and the time intervals when they are needed don't overlap is a common practice when coding with DX12 or Vulkan. However, it is not a good idea to create and destroy such placed buffer or texture every frame. I recommend to:

- Allocate a piece of memory large enough to fit your largest resource using `Allocator::AllocateMemory`.
- Create all resources that you need, placed in that region of memory, using `Allocator::CreateAliasingResource`.
- In each frame, only use the resources you need, don't create od destroy them every time. Also don't forget to issue aliasing barriers when switching to using another one.

Custom pools feature of the library is commonly over-used and usually not needed, also likely in your case.

If you really need to defer deletion of some resource or memory allocation to N, N+1, N+2 frames, this is out of scope of this library and should be done by the user.

**Comment by lmagder** [comment]
Thanks for the detailed answer. What you're saying makes sense and yeah it looks like I would need to pool the resources to avoid spamming creating and destroying them.
 
I was kind of hoping there was a way of using the allocator to determine the aliasing groups you mention in the first step since possibly one large resource could also alias to two smaller ones stored sequentially. So that's where my thinking of treating the liveness as an "allocation" from the libraries POV even though it actually wouldn't be due to the deferred free. But maybe this is outside its scope and I need to use a virtual block allocator instead, although those won't resize by creating sub blocks the way a pool would.

**Comment by adam-sawicki-a** [comment]
To automatically determine what resources can alias (as well as how to optimally schedule render passes and barriers), I recommend using our another technology: **[Render Pipeline Shaders](https://gpuopen.com/rps/)**.

**Comment by lmagder** [comment]
Thanks, I'll check it out for inspiration, although I already have a working render graph. Thanks for answering my questions though
