### ISSUE TITLE
Update vcpkg port

### ISSUE THREAD

**Issue by phoekz** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#54]
The latest vcpkg port is on `10f148cef0dfd34ae1a9373b9396beb1581c992a`, which seems to be a bit over two years old:

```
// D3D12MemAlloc.h

<b>Version 2.0.0-development</b> (2021-03-11)
```

**Comment by adam-sawicki-a** [comment]
I am sorry but vcpkg port is not managed by us. This library is offered through this GitHub repository. Every port or binding to a different programming language or distribution platform is out of scope. We welcome external contributions and we can link to them from README, as we do in this case.
