### ISSUE TITLE
BlockMetadata_TLSF::WriteAllocationInfoToJson

### ISSUE THREAD

**Issue by ttcvetkov** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#67]
https://github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator/blob/e00c4a7c85cf9c28c6f4a6cc75032736f416410f/src/D3D12MemAlloc.cpp#L5033

Why do you cast uint64 to bool?

**Comment by adam-sawicki-a** [comment]
As far as I remember, this is a trick to make the value count as 0 or 1, so that the argument value is increased by one when `m_NullBlock->size` is not zero.

Do you observe any problem with this expression? Some error or warning in your compiler?

**Comment by adam-sawicki-a** [comment]
I hopefully fixed this warning.
