### ISSUE TITLE
MSAA never using small alignment

### ISSUE THREAD

**Issue by darwikey** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#68]
Hi!
In the CanUseSmallAlignment function, I have noticed the  
```cpp
    if (resourceDesc.SampleDesc.Count > 1)
        return false;
```
That prevent MSAA textures to use small alignment optim. But after in the code there is that:
```cpp
        && CanUseSmallAlignment(inOutResourceDesc)
#endif
        )
    {
        /*
        The algorithm here is based on Microsoft sample: "Small Resources Sample"
        https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12SmallResources
        */
        const UINT64 smallAlignmentToTry = inOutResourceDesc.SampleDesc.Count > 1 ?
            D3D12_SMALL_MSAA_RESOURCE_PLACEMENT_ALIGNMENT :
            D3D12_SMALL_RESOURCE_PLACEMENT_ALIGNMENT;
```
And it seems to use the correct alignment for MSAA textures.

It is an issue for our game because we use several small textures with MSAA, that are probably aligned on 4MB without this optimization

**Comment by adam-sawicki-a** [comment]
I agree function `CanUseSmallAlignment` is overly conservative. Please try compiling your project with macro `D3D12MA_USE_SMALL_RESOURCE_PLACEMENT_ALIGNMENT=2` and see if it helps.

**Comment by darwikey** [comment]
Actually these textures are used as render target, so they can't use the small alignement optim. 
So my question wasn't relevant.
Thanks anyway for your help !
