### ISSUE TITLE
ComPtr support

### ISSUE THREAD

**Issue by matt77hias** [GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator#7]
Is it possible to let the `D3D12MA::Allocator` inherit from `IUnknown` and provide implementations for `AddRef` (this won't conflict with the current use of the member method, `AddRef`), `Release` and `QueryInterface` to be used with Microsoft's intrusive `ComPtr`? This would be consistent with D3D12 types themselves and with 3th-party tools such as DirectXShaderCompiler which also mimic this former behavior.

**Comment by adam-sawicki-a** [comment]
I was thinking about making the classes of the library real COM objects inheriting from `IUnknown`, but I decided not to, because that would have some memory and performance overhead for using virtual function table etc. While the `Allocator` object could be a COM object, `Allocation`-s should be small and fast. What do you think?

**Comment by matt77hias** [comment]
Good points. As an alternative, why not use the destructor for releasing (as well)? If the destructors are public instead, the callee can use whatever he/she prefers (`std::unique_ptr`/`std::shared_ptr` without requiring a custom deleter for this library only, or just put it on the stack (as the destructor is non-virtual and no virtual inheritance is involved). The benefit is that most of the callee's own destructors can be explicitly defined as `= default`.

**Comment by adam-sawicki-a** [comment]
I'd love the library objects to be deleted with just the destructor. Problem is that `Allocation` objects are created out of a free-list pool and all other objects (`Allocator`, `Pool`) may be allocated using custom, user-provided CPU heap allocation functions, which is needed because many game developers use them in their engines. How to make it working with default destructor?

**Comment by matt77hias** [comment]
I do not mean using a default destructor in `D3D12MemoryAllocator` itself, but in the applications/libraries depending on `D3D12MemoryAllocator`, which as of writing is not possible as one needs to directly or indirectly (using a custom smart pointer) call `Release`.

**Comment by matt77hias** [comment]
I just found a good generic solution for this ubiquitous problem. Apparently, there is something called [`unique_resource`](https://en.cppreference.com/w/cpp/experimental/unique_resource) added to [LFTS v3](https://en.cppreference.com/w/cpp/experimental/lib_extensions_3) that can be used for arbitrary resource RAII (similiar to `unique_ptr` for memory resource RAII). 

* `unique_resource` is not intrusive and thus does not impose a certain interface on the resource (compared to `ComPtr`);
* `unique_resource` does not require a pointer-like resource (compared to `unique_ptr`), but can just store the resource by value (e.g., `handle`, `Allocation`);
* `unique_resource` is pretty light weight with regard to size (resource + deleter + `bool`) (in case of empty base optimization, this would just be resource + `bool` for `D3D12MA`'s purposes);
* `unique_resource` is pretty light weight with regard to [includes](https://raw.githubusercontent.com/PeterSommerlad/scope17/master/scope.hpp).

Of course, nothing is restricting a user of `D3D12MA` to use or not use `unique_resource` (i.e. it does not need to be embedded in the API of this library), so I am going to close this issue.

**Comment by adam-sawicki-a** [comment]
Thanks for this conclusion. I can see the `unique_resource` is experimental, while `std::unique_ptr` can also work with custom deleters and can even work with handles which are not pointers. See for example https://www.asawicki.info/news_1494_unique_ptr_in_visual_c_2010

I still plan to consider whether the way of destruction of D3D12MA objects can be improved, e.g. by maybe using standard destructor and overloaded member `operator delete`, or something else, so ideas are welcomed.

**Comment by matt77hias** [comment]
True, though much pointer-like semantics is added like the [`std::nullptr_t` constructor](https://stackoverflow.com/a/47724311/1731200) and comparison and logical operators. But you're right that there is quite a resemblance between `unique_resource` and `unique_ptr`.

Some insightful presentation about [`unique_resource`](https://www.youtube.com/watch?v=O1sK__G5Nrg). I am not that convinced by his arguments, however, that `std::FILE` and Windows `HANDLE` are not suited for `unique_ptr`.
